sudo: required
services:
  - docker

before_install:
  - docker build -t philipjesic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true philipjesic/docker-react npm run test -- --coverage